language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sudo apt-get update
  - sudo apt-get -y --force-yes upgrade
  - curl -s http://getcomposer.org/installer | php
  - php -n composer.phar install --dev --verbose

script: phpunit
